name: restaurant_universitaire
description: Application mobile Flutter pour la gestion des repas au restaurant universitaire
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  mask_text_input_formatter: ^2.9.0
  #url_launcher: ^6.3.2
  #webview_flutter: ^4.13.0
  #supabase_flutter: ^2.9.1
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  cloud_firestore: ^6.0.0
  firebase_database: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - images/
